### ISSUE TITLE
用oicq-template跑起来的，滑块登录遇到问题

### ISSUE THREAD

**Issue by Kun-GitHub** [takayama-lily/oicq-template#5]
收到滑动验证码，请访问以下地址完成滑动，并从网络响应中取出ticket输入。
=======================================================
没法输入，在哪输入？vs code跟webstorm 都没窗口输入，被禁了，怎么解决？

**Comment by Kun-GitHub** [comment]
问题已解决，谢谢。
问题已解决，谢谢。

**Comment by lisanyao** [comment]
> 问题已解决，谢谢。 问题已解决，谢谢。

兄弟，我也遇到同样的问题，应该怎么解决 @Kun-GitHub

**Comment by lisanyao** [comment]
"use strict"
const { createClient } = require("oicq")

const account = 123456789    // 替换成自己的账号
const password = "123456789" // 替换成自己的密码

const bot = createClient(account)

bot.on("system.login.slider", function (e) {
  console.log("输入ticket：")
  process.stdin.once("data", ticket => {
    this.submitSlider(String(ticket).trim())
  })
}).on("system.login.qrcode", function (e) {
  this.logger.mark("扫码后按Enter完成登录")
  process.stdin.once("data", () => {
    this.login()
  })
}).login(password)

exports.bot = bot

**Comment by lisanyao** [comment]
修改index.js后可以输入ticket，但是提示QQ版本过低
